name: asap_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^6.1.0
  cupertino_icons: ^1.0.0
  equatable: ^1.2.3
  flutter_bloc: ^6.1.0
  flutter_svg:
  font_awesome_flutter: ^8.4.0
  formz: ^0.3.0
  google_fonts: ^1.1.0
  meta: ^1.1.8
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
